Added new features (write, buffer, commit) for the ReadWrite channel …
ni/niveristand-custom-device-inline-async-api pull request #7
Opened 2019-04-29 14:27 UTC by eatondan

…type.

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-inline-async-api/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-inline-async-api/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

TODO: Include high-level description of the changes in this pull request.

### Why should this Pull Request be merged?

TODO: Justify why this contribution should be part of the project.

### What testing has been done?

TODO: Detail what testing has been done to ensure this submission meets requirements.

2019-04-29 14:36 UTC, rtzoeller commented
Thanks @eatondan for the pull request! Please complete the pull request template so we can better understand the changes it includes and the motivation behind them.

2019-04-29 15:40 UTC, eatondan commented
@rtzoeller  
Updated. Thanks!

2019-04-30 20:32 UTC, csjall commented
I am confused by the changes in ReadWrite.ProcessData.Read.vi. 
![image](https://user-images.githubusercontent.com/4081815/56990936-0f567b80-6b5c-11e9-8794-fd0e50437981.png)

- [ ] In the previous revision we used the greater than comparison, but now we are using not equal to. Why did the comparison change?
- [ ] The logic for the "Ignore Reset Values?" terminal seems reversed. In the true case we are referring to the reset values. I would not expect to reference the reset values when we are ignoring them.

In ReadWrite.ProcessData.vi 
![image](https://user-images.githubusercontent.com/4081815/56991224-c3580680-6b5c-11e9-8fd8-a2a9f30d1d4d.png)
- [ ] This VI still has the old implementation of calculating "Detect?" array. Should this VI be updated to match the implementation in Read.vi.

2019-05-01 13:04 UTC, eatondan commented
The original version of the read/write channel type was designed as a trigger. So, the write (or reset) was always 0. Therefore, a greater than was an easy comparison. Part of the update is to allow the user to write values other than zero. This means the comparison had to be updated. 

The Ignore Reset Value allows the original trigger like functionality by ignoring the reset. Again, the original trigger method would go from 0 to 1 and then reset from 1 to 0. The greater than implementation would trigger on the 0 to 1 and not the 1 to 0. This new triggering method also the user to either trigger the original way by ignoring the 1 to 0 (ignore reset value) or trigger on both.

The ProcessData uses the old implementation (greater than) because it doesn't because it doesn't allow the user to explicitly write. It is just a read and reset to 0 (trigger function). The new function is a separate read that can be used with a separate write.

2019-05-01 14:53 UTC, buckd requested changes
- [ ] All the VIs you created/modified had their Source Only setting changed. All of these VIs should keep their source separated.
- [ ] Is there a reason `ReadWrite.lvclass:ReadWrite.ProcessData.Write.vi` re-implements the `Buffer` and `Commit` VI logic instead of just calling those subVIs?

2019-05-01 14:53 UTC, buckd commented on Source/vi.lib/NI/NIVS Inline Async API/_Data Access Engine/Access Type Classes/ReadWrite/ReadWrite.lvclass
> +	<Property Name="NI.LV.All.SourceOnly" Type="Bool">false</Property>
Source should still be separated.

2019-05-01 14:53 UTC, buckd commented on Source/vi.lib/NI/NIVS Inline Async API/_Data Access Engine/Data Access Engine/Data Access Engine.lvclass
> +	<Property Name="NI.LV.All.SourceOnly" Type="Bool">false</Property>
Source should still be separated.

2019-05-02 12:35 UTC, eatondan commented on Source/vi.lib/NI/NIVS Inline Async API/_Data Access Engine/Access Type Classes/ReadWrite/ReadWrite.lvclass
> +	<Property Name="NI.LV.All.SourceOnly" Type="Bool">false</Property>
Fixed and recommitted.

2019-05-02 12:36 UTC, eatondan commented on Source/vi.lib/NI/NIVS Inline Async API/_Data Access Engine/Data Access Engine/Data Access Engine.lvclass
> +	<Property Name="NI.LV.All.SourceOnly" Type="Bool">false</Property>
Fixed and recommitted.

2019-05-02 12:40 UTC, eatondan commented
On "Is there a reason ReadWrite.lvclass:ReadWrite.ProcessData.Write.vi re-implements the Buffer and Commit VI logic instead of just calling those subVIs?". The classes are not compatible. You can't directly re-use and re-wire.

2019-05-02 13:15 UTC, buckd commented
> The classes are not compatible. You can't directly re-use and re-wire.

The VIs are in the same class. This code looks identical:
![image](https://user-images.githubusercontent.com/29306186/57077450-b567ca00-6cb1-11e9-899c-5177b1b6dbc6.png)

If one part of the implementation has to change, we now have to change it in two places. By reusing the subVIs, there is only one location that must be updated.
![image](https://user-images.githubusercontent.com/29306186/57077676-3f179780-6cb2-11e9-8aeb-d787af6975e0.png)

2019-05-02 20:49 UTC, csjall commented
It still feels like the Boolean logic is inverted. If "Ignore Reset Values?" is true, why are we evaluating the reset values when detecting a change? In my mind the true/false case should be swapped.
![image](https://user-images.githubusercontent.com/4081815/57105891-9852eb80-6cf1-11e9-8d10-be3b019a3539.png)

2019-05-06 13:16 UTC, eatondan commented
On the buffer and commit, I see what you mean now.  I can make that change.

2019-05-06 13:19 UTC, eatondan commented
On the inverted logic, we need to use the reset values to ignore them. The logic should be don't allow (ignore) any triggering (detection) when the written values match the reset values. If you want to change the wording of the input, I am happy to do that. Just let me know what makes more sense.

Thank you for all the help in this! I really appreciate it!

2019-05-06 13:41 UTC, csjall commented
Go ahead and change the name of the terminal to be concise but precise.

2019-05-06 13:58 UTC, eatondan commented
I could make it "Do Not Detect Reset". Thoughts?

2019-05-06 15:25 UTC, csjall commented
I prefer affirmative names like "Detect Reset Value" or "Ignore Reset Value" as opposed to "Do Not Detect Reset Value". I would rather flip the case structure than add the word "Do Not" as a prefix.

@tannerblair and I were talking about this. It seems the goal is to detect/ignore a reset value condition. Could the Reset Value SubVI set a boolean flag when the values is reset. This boolean flag can be evaluated and cleared the next time we Read the values. What is the benefit of cheecking all the reset values for a trigger condition as opposed to checking a single boolean?

2019-05-06 16:20 UTC, eatondan commented
I agree on the affirmative names. I should have done that initially. However, I really don't want to switch the cases because it would break released code. It should have been Detect Reset and cases flipped. Now that it is released, it should be left as is or changed to Do Not Detect Reset. Thoughts?

On the reset flag. That would be something you need to save per channel. Each array element can be individually reset. So, you would end up with a reset detection array. It isn't much different than what I already have. The checking is the easiest, most robust way to handle it.

2019-05-06 16:53 UTC, csjall commented
How is this released already. I thought the Ignore Reset Value is a new terminal.

2019-05-06 16:55 UTC, eatondan commented
I didn't know you branched my API. A customer needed new features. I added them to my branch. Tanner let me know about this version of the branch last week and asked me to merge them and deprecate mine. That is what I am trying to do.

2019-05-06 18:39 UTC, csjall commented
No worries. Go ahead and submit a pull request with name.

2019-05-07 14:53 UTC, eatondan commented
Add updated the repo based on our discussion. Do I need to close this pull request and do another one?

2019-05-07 19:47 UTC, csjall commented
You can keep this pull request. The pull request is automatically updated when you submit changes to your master branch.

2019-05-08 13:45 UTC, buckd reviewed
There are still 3 files that do not have source separated. Other than this, everything looks good.
- [ ] `Data Access Engine.lvclass`
- [ ] `ReadWrite.lvclass`
- [ ] `Data Access Engine.lvclass:Data.Process.Execute.vi`

2019-05-08 15:32 UTC, eatondan commented
I apologize. Those are now updated as well.

2019-05-08 15:32 UTC, eatondan commented
I apologize. I updated those now. Thank you for the catch.

2019-05-08 16:11 UTC, buckd approved these changes

2019-05-08 16:22 UTC, merged